# Generated by Django 4.2.7 on 2023-11-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_students_tichers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(through='school.Students_tichers', to='school.teacher'),
        ),
    ]
