# Generated by Django 4.2.7 on 2023-11-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_student_teachers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students_tichers',
        ),
    ]
